## Numpy 更利于科学计算及多维数组操作

In [5]:
import numpy as np
height=[1.73,1.68,1.71,1.89,1.79]
np_height=np.array(height)
np_height

array([ 1.73,  1.68,  1.71,  1.89,  1.79])

In [6]:
weight=[65.4,59.2,63.6,88.4,68.7]
np_weight=np.array(weight)
np_weight

array([ 65.4,  59.2,  63.6,  88.4,  68.7])

In [7]:
bmi=np_weight/np_height ** 2
bmi

array([ 21.85171573,  20.97505669,  21.75028214,  24.7473475 ,  21.44127836])

## 通过布尔值获得Numpy子集

In [8]:
bmi

array([ 21.85171573,  20.97505669,  21.75028214,  24.7473475 ,  21.44127836])

In [9]:
bmi[1]

20.975056689342409

In [10]:
bmi>23

array([False, False, False,  True, False], dtype=bool)

In [12]:
bmi[bmi>23]

array([ 24.7473475])

## Numpy操作2维数组
numpy对象的shape属性可以获得数组形状
numpy数组的成员必须是同一数据类型，否则会发生隐含转换，或者报错

In [13]:
np_2d=np.array([[1.73,1.68,1.71,1.89,1.79],
               [65.4,59.2,63.6,88.4,68.7]])
np_2d

array([[  1.73,   1.68,   1.71,   1.89,   1.79],
       [ 65.4 ,  59.2 ,  63.6 ,  88.4 ,  68.7 ]])

In [14]:
np_2d.shape

(2, 5)

In [16]:
np.array([[1.73,1.68],
         ["3.4",8.9]])#必须是同一数据类型，全部转化为字符串类型

array([['1.73', '1.68'],
       ['3.4', '8.9']],
      dtype='<U32')

In [20]:
np_2d

array([[  1.73,   1.68,   1.71,   1.89,   1.79],
       [ 65.4 ,  59.2 ,  63.6 ,  88.4 ,  68.7 ]])

In [21]:
np_2d[0]

array([ 1.73,  1.68,  1.71,  1.89,  1.79])

In [22]:
np_2d[0][2]#取第1行，第3列

1.71

In [23]:
np_2d[0,2]#取第1行，第3列

1.71

## Numpy基本描述统计命令
mean 均值
median 中值
corrcoef 相关系数
std 标准差

In [26]:
np.mean(np_height)

1.7600000000000002

In [27]:
np.median(np_height)

1.73

In [28]:
np.corrcoef(np_height,np_weight)

array([[ 1.        ,  0.97514969],
       [ 0.97514969,  1.        ]])

In [29]:
np.std(np_height)

0.074296702484026825

## Numpy产生正态分布随机数

### random.normal(均值，标准差，数量)
### column_stack表示按列堆叠数据，注意传入的两个数组要用括号组织成tuple传入

In [32]:
height=np.round(np.random.normal(1.75,0.20,5000),2)
weight=np.round(np.random.normal(60.32,15,5000),2)
np_city=np.column_stack((height,weight))
np_city

array([[  1.85,  61.74],
       [  1.41,  75.49],
       [  1.77,  78.18],
       ..., 
       [  2.09,  47.29],
       [  1.32,  74.83],
       [  1.85,  63.44]])